version: '3.6'

services: 
  database:
    image: postgres
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=${POSTGRES_USER:-marketplace}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-marketplace}
      - POSTGRES_DB=${POSTGRES_DB:-marketplace}
