name: Build Develop Push
on:
  push:
    tags:
      - 'develop-v*.*.*'
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: 
      name: develop
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref:  main
          ###There isn't a develop branch yet. Change as needed
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Login to ECR
        uses: docker/login-action@v1 
        with:
          registry: 242357350604.dkr.ecr.sa-east-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      - name: Build and push - Rapidpro Image
        id: docker_build1
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: 242357350604.dkr.ecr.sa-east-1.amazonaws.com/push-backend:marketplace-engine-${{ steps.vars.outputs.tag }}
          no-cache: true
