name: Build Integrations Engine in SHARED
on:
  workflow_dispatch:
    inputs:
      source-branch:
        description: 'Source branch (master, staging, develop, etc.)'
        required: true
        default: 'main'
      tag-name:
        description: 'Tag id (v0.0.1-develop, v0.0.2, etc.)'
        required: true
      destination-env:
        description: 'Destination environment (production, develop)'
        required: true
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          repository: Ilhasoft/weni-integrations-engine
          ref: ${{github.event.inputs.source-branch}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ECR
        uses: docker/login-action@v1 
        with:
          registry: 869898323958.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID_SHARED }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY_SHARED }}
      - name: Build and push - Integrations Engine Image
        id: docker_build1
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: 869898323958.dkr.ecr.us-east-1.amazonaws.com/push-backend:integrations-engine-${{github.event.inputs.tag-name}}
          no-cache: true
      - name: Check out Kubernetes Manifests
        uses: actions/checkout@master
        with:
          ref: main
          repository: Ilhasoft/kubernetes-manifests
          token: ${{ secrets.CICEROW_GITHUB_PERMANENT_TOKEN }}
          path: ./kubernetes-manifests/
      - name: Update image deployment 01
        run: |
            sudo apt update
            sudo apt install -y jq
            echo 'Old image to replace:'
            cat ./kubernetes-manifests/integrations/${{github.event.inputs.destination-env}}/deployment-engine.json|jq '.[3].value'
            echo 'New configurations:'
            new_configuration=$(cat ./kubernetes-manifests/integrations/${{github.event.inputs.destination-env}}/deployment-engine.json|jq '.[3].value = "869898323958.dkr.ecr.us-east-1.amazonaws.com/push-backend:integrations-engine-${{github.event.inputs.tag-name}}"')
            echo "$new_configuration"
            echo "$new_configuration" > ./kubernetes-manifests/integrations/${{github.event.inputs.destination-env}}/deployment-engine.json
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.CICEROW_GITHUB_PERMANENT_TOKEN }}
          repository: Ilhasoft/kubernetes-manifests
          directory: ./kubernetes-manifests/
          branch: main